export const CATEGORIES = [
  { id: "all",           label: "All" },
  { id: "animated",      label: "Animated" },
  { id: "shadcn",        label: "shadcn" },
  { id: "tailwind",      label: "Tailwind" },
  { id: "react",         label: "React" },
  { id: "vue-svelte",    label: "Vue / Svelte" },
  { id: "angular",       label: "Angular" },
  { id: "headless",      label: "Headless" },
  { id: "css",           label: "CSS / HTML" },
  { id: "collections",   label: "Collections" },
  { id: "design-tools",  label: "Design Tools" },
  { id: "dev-tools",     label: "Dev Tools" },
  { id: "inspiration",   label: "Inspiration" },
];

export const CAT_RESOLVE = (cat) => cat === "multi" ? "vue-svelte" : cat;
export const STACK_FILTERS = ["all", "React", "Tailwind", "Vue", "Svelte", "CSS", "Design"];
export const SORT_OPTIONS = [
  { id:"featured", label:"Curated order" },
  { id:"newest", label:"Newest first" },
  { id:"az", label:"A → Z" },
];

// Category accent colors — muted ink tones, not neon
export const CAT_COLOR = {
  animated:      "#B85C2C",
  shadcn:        "#2E7D52",
  tailwind:      "#1B6CA8",
  css:           "#7A5C1E",
  react:         "#1A6B7A",
  angular:       "#A02525",
  headless:      "#5B3A8A",
  "vue-svelte":  "#2A7A5A",
  multi:         "#2A7A5A",
  collections:   "#8A3A6A",
  "design-tools":"#6A3A8A",
  "dev-tools":   "#2A6A6A",
  inspiration:     "#8A5A2A",
};

export const LIB_STACKS = {
  1:["React","Tailwind"], 2:["React","Tailwind"], 3:["React"],
  4:["React","Tailwind"], 5:["React","shadcn"],   6:["React"],
  7:["React"],            8:["React","Tailwind"], 9:["React"],
  10:["React","shadcn"],  11:["React"],           12:["React","Tailwind"],
  13:["React","Tailwind"],15:["React"],
  16:["React","shadcn"],  17:["React","shadcn"],  18:["React","shadcn"],
  19:["React","shadcn"],  20:["React","shadcn"],  21:["React","shadcn"],
  22:["React","shadcn"],  23:["React","shadcn"],  24:["React","shadcn"],
  25:["React","shadcn"],  26:["React","shadcn"],  27:["React","shadcn"],
  28:["React","shadcn"],  79:["React","shadcn"],
  29:["Tailwind"],        30:["Tailwind","React","Vue"],
  31:["Tailwind"],        32:["Tailwind"],        33:["Tailwind"],
  77:["Tailwind"],        78:["React","Tailwind"],34:["Tailwind"],
  35:["Tailwind"],        36:["Tailwind"],        37:["Tailwind"],
  38:["Tailwind"],        39:["Tailwind"],
  40:["CSS"],             41:["React","shadcn"],  42:["CSS"],
  43:["React","Tailwind"],44:["React","shadcn"],  45:["CSS"],
  46:["CSS"],             47:["CSS"],             48:["CSS"],
  49:["React"],  50:["React"],  51:["React"],  52:["React"],
  53:["React"],  54:["React"],  75:["React","Tailwind"],
  80:["React"],  81:["React"],  82:["React"],  83:["React"],
  85:["React"],  55:["React"],  56:["React"],  57:["React"],
  95:["Angular"],  96:["Angular"],  97:["Angular"],
  58:["React"],  59:["React","Vue"],  60:["React"],
  61:["React"],  84:["React","Vue","Svelte"],
  14:["Vue"],    62:["Svelte"],  63:["Svelte"],
  76:["React","Vue","Svelte"],  64:["Vue"],  65:["Vue"],  93:["Vue"],
  66:["React","Tailwind"],  67:["React","Tailwind","shadcn"],  68:["React"],
  70:["CSS","Tailwind"],  71:["CSS"],   87:["Design"],
  91:["Design"],          94:["CSS"],   86:["Design"],  90:["Design"],
  72:["React"],  73:["React","Vue","Svelte"],  88:["React","Vue"],  89:["Design"],
  98:["Tailwind"],  99:["React"],  100:["React"],
  101:["Design"],   102:["Design"], 103:["Design","CSS"],
  104:["Tailwind"], 105:["Design","CSS"],
  137:["Design"], 138:["Design"], 139:["Design"], 140:["Design"], 141:["Design"], 142:["Design"], 143:["Design"], 144:["Design"],
  145:["Design"], 146:["Design"], 147:["Design"], 148:["CSS"], 149:["Design"], 150:["React"], 151:["Vue"], 152:["React","Tailwind"],
};

export const LIBS = [
  { id:1,  name:"Aceternity UI",        url:"ui.aceternity.com",                   cat:"animated",      desc:"Stunning animated components built with Tailwind CSS and Framer Motion", added:"2024-01" },
  { id:2,  name:"Magic UI",             url:"magicui.design",                      cat:"animated",      desc:"150+ free animated React components for marketing sites and SaaS products", added:"2024-02" },
  { id:3,  name:"Motion Primitives",    url:"motion-primitives.com",               cat:"animated",      desc:"Copy-paste motion primitives for building beautiful animated React interfaces", added:"2024-03" },
  { id:4,  name:"Eldora UI",            url:"eldoraui.site",                       cat:"animated",      desc:"Animated React components inspired by shadcn/ui, Aceternity UI, and Magic UI", added:"2024-04" },
  { id:5,  name:"Cult UI",              url:"cult-ui.com",                         cat:"animated",      desc:"Animated React components built on shadcn/ui with a dark-mode-first aesthetic", added:"2024-05" },
  { id:6,  name:"Animata",              url:"animata.design",                      cat:"animated",      desc:"Hand-crafted interaction and animation components for creative interfaces", added:"2024-06" },
  { id:7,  name:"UI Layout",            url:"ui-layout.com",                       cat:"animated",      desc:"Complex layout patterns with smooth animation support for React apps", added:"2024-07" },
  { id:8,  name:"Lukacho UI",           url:"ui.lukacho.com",                      cat:"animated",      desc:"Minimal animated UI kit for modern React apps", added:"2024-08" },
  { id:9,  name:"ReactBits",            url:"reactbits.dev",                       cat:"animated",      desc:"Animated React components for creative, expressive UIs", added:"2024-09" },
  { id:10, name:"SmoothUI",             url:"smoothui.dev",                        cat:"animated",      desc:"130+ micro-interaction components built on Motion, compatible with shadcn/ui", added:"2024-10" },
  { id:11, name:"Fancy Components",     url:"fancycomponents.dev",                 cat:"animated",      desc:"Distinctive animated component collection for creative developers", added:"2024-11" },
  { id:12, name:"CuiCui",               url:"cuicui.day",                          cat:"animated",      desc:"Daily component drops with polished motion design", added:"2024-12" },
  { id:13, name:"SyntaxUI",             url:"syntaxui.com",                        cat:"animated",      desc:"Animated component library with live code previews and Tailwind integration", added:"2024-13" },
  { id:15, name:"UI Labs",              url:"uilabs.dev",                          cat:"animated",      desc:"Experimental fine UI — carefully crafted React components and interactions", added:"2024-15" },
  { id:16, name:"shadcn/ui",            url:"ui.shadcn.com",                       cat:"shadcn",        desc:"The gold standard — accessible components installed via CLI into your own codebase", added:"2023-01" },
  { id:17, name:"21st.dev",             url:"21st.dev",                            cat:"shadcn",        desc:"The npm for design engineers — component registry with thousands of community components", added:"2024-01" },
  { id:18, name:"Origin UI",            url:"originui.com",                        cat:"shadcn",        desc:"Beautiful SaaS-focused shadcn/ui components built with a design-first approach", added:"2024-02" },
  { id:19, name:"Shadcnblocks",         url:"shadcnblocks.com",                    cat:"shadcn",        desc:"1,700+ full page sections and blocks for shadcn/ui projects", added:"2024-03" },
  { id:20, name:"HextaUI",              url:"hextaui.com",                         cat:"shadcn",        desc:"Modern shadcn/ui extensions with refined aesthetics and smooth animations", added:"2024-04" },
  { id:21, name:"KokonutUI",            url:"kokonutui.com",                       cat:"shadcn",        desc:"Accessible, production-ready shadcn/ui component extensions", added:"2024-05" },
  { id:22, name:"Bundui",               url:"bundui.io",                           cat:"shadcn",        desc:"Curated shadcn/ui component bundles ready to drop into your project", added:"2024-06" },
  { id:23, name:"Skiper UI",            url:"skiper-ui.com",                       cat:"shadcn",        desc:"24 free animated components built on top of shadcn/ui", added:"2024-07" },
  { id:24, name:"lndev/ui",             url:"ui.lndev.me",                         cat:"shadcn",        desc:"Indie-crafted shadcn/ui extensions with a unique visual personality", added:"2024-08" },
  { id:25, name:"ReUI",                 url:"reui.io",                             cat:"shadcn",        desc:"Enterprise-grade shadcn/ui extensions with Radix and Base UI support", added:"2024-09" },
  { id:26, name:"MynaUI",               url:"mynaui.com",                          cat:"shadcn",        desc:"Elegant shadcn/ui components with consistent visual language", added:"2024-10" },
  { id:27, name:"BadtzUI",              url:"badtz-ui.com",                        cat:"shadcn",        desc:"Core-free shadcn/ui extensions updated every week", added:"2024-11" },
  { id:28, name:"Nyxb UI",              url:"nyxbui.design",                       cat:"shadcn",        desc:"Dark-mode-first shadcn/ui components with rich motion and expressive design", added:"2024-12" },
  { id:79, name:"Kibo UI",              url:"kibo-ui.com",                         cat:"shadcn",        desc:"Advanced shadcn/ui registry: color pickers, QR codes, drag-drop uploaders", added:"2024-13" },
  { id:29, name:"DaisyUI",              url:"daisyui.com",                         cat:"tailwind",      desc:"The most popular Tailwind CSS component library — 65 components, 35 themes", added:"2021-01" },
  { id:30, name:"Flowbite",             url:"flowbite.com",                        cat:"tailwind",      desc:"Tailwind component library with React, Vue, Svelte adapters and a Figma kit", added:"2021-02" },
  { id:31, name:"Preline UI",           url:"preline.co",                          cat:"tailwind",      desc:"Fully responsive Tailwind HTML components with Alpine.js interactivity", added:"2022-01" },
  { id:32, name:"HyperUI",              url:"hyperui.dev",                         cat:"tailwind",      desc:"Free Tailwind components for ecommerce, marketing, and application UIs", added:"2022-02" },
  { id:33, name:"Meraki UI",            url:"merakiui.com",                        cat:"tailwind",      desc:"RTL-supported Tailwind CSS UI components", added:"2022-03" },
  { id:77, name:"Sailboat UI",          url:"sailboatui.com",                      cat:"tailwind",      desc:"150+ Tailwind CSS components with Alpine.js interactivity", added:"2023-01" },
  { id:78, name:"TailGrids",            url:"tailgrids.com",                       cat:"tailwind",      desc:"600+ React + Tailwind components, blocks, and templates", added:"2023-02" },
  { id:34, name:"FlyonUI",              url:"flyonui.com",                         cat:"tailwind",      desc:"Semantic Tailwind components on DaisyUI and Alpine.js", added:"2023-03" },
  { id:35, name:"Penguin UI",           url:"penguinui.com",                       cat:"tailwind",      desc:"Simple, clean, and accessible Tailwind CSS components", added:"2023-04" },
  { id:36, name:"Tailkits",             url:"tailkits.com",                        cat:"tailwind",      desc:"Curated Tailwind CSS component marketplace", added:"2023-05" },
  { id:37, name:"Tailus HTML",          url:"html.tailus.io",                      cat:"tailwind",      desc:"Tailwind CSS components with refined design standards and P3 color support", added:"2023-06" },
  { id:38, name:"DevUI",                url:"devui.in",                            cat:"tailwind",      desc:"Developer-centric Tailwind components with a code-first DX", added:"2023-07" },
  { id:39, name:"Tailblocks",           url:"tailblocks.cc",                       cat:"tailwind",      desc:"Ready-to-use Tailwind CSS blocks for rapid prototyping", added:"2021-03" },
  { id:40, name:"Uiverse",              url:"uiverse.io",                          cat:"css",           desc:"Thousands of community-created CSS elements and components", added:"2022-01" },
  { id:41, name:"Dot Matrix",           url:"dotmatrix.zzzzshawn.cloud",           cat:"css",           desc:"55+ dot-matrix loaders built with React, TypeScript, Tailwind, and shadcn", added:"2026-01" },
  { id:42, name:"Shapes Gallery",       url:"shapes.gallery",                      cat:"css",           desc:"Pure CSS shape collection for creative backgrounds and flourishes", added:"2023-01" },
  { id:43, name:"RareUI",               url:"rareui.com",                          cat:"css",           desc:"Rare animated React components built with Tailwind and Motion", added:"2024-01" },
  { id:44, name:"Indie Starter UI",     url:"ui.indie-starter.dev",               cat:"css",           desc:"Minimal React + shadcn components for indie developers who want to ship fast", added:"2024-02" },
  { id:45, name:"FlashUI",              url:"flashui.site",                        cat:"css",           desc:"Zero-install paste-and-go CSS UI elements", added:"2024-03" },
  { id:46, name:"Ever UI",              url:"ever-ui.com",                         cat:"css",           desc:"Evergreen CSS components built for long-term browser support", added:"2024-04" },
  { id:47, name:"Chakra Framer",        url:"chakraframer.com",                    cat:"css",           desc:"CSS motion templates inspired by Framer's design system", added:"2024-05" },
  { id:48, name:"Ground Bossadizenith", url:"ground.bossadizenith.me",            cat:"css",           desc:"Experimental CSS ground-level components and visual effects", added:"2024-06" },
  { id:49, name:"HeroUI",               url:"heroui.com",                          cat:"react",         desc:"Beautiful React components (formerly NextUI) — 100+ accessible, themeable components", added:"2022-01" },
  { id:50, name:"Mantine",              url:"mantine.dev",                         cat:"react",         desc:"Feature-rich React library with 100+ components and 50+ hooks", added:"2021-01" },
  { id:51, name:"Chakra UI",            url:"chakra-ui.com",                       cat:"react",         desc:"Accessible, composable React components with dark mode out of the box", added:"2020-01" },
  { id:52, name:"PrimeReact",           url:"primereact.org",                      cat:"react",         desc:"90+ React UI components with rich theming support", added:"2019-01" },
  { id:53, name:"MUI",                  url:"mui.com",                             cat:"react",         desc:"The most widely used React UI framework — Material Design and Joy UI systems", added:"2016-01" },
  { id:54, name:"Ant Design",           url:"ant.design",                          cat:"react",         desc:"Enterprise-grade React UI library from Alibaba", added:"2016-02" },
  { id:75, name:"Tremor",               url:"tremor.so",                           cat:"react",         desc:"35+ React components for dashboards — charts, KPI cards, data tables", added:"2023-01" },
  { id:80, name:"Fluent UI",            url:"react.fluentui.dev",                 cat:"react",         desc:"Microsoft's React library with 950+ cross-platform components", added:"2020-01" },
  { id:81, name:"Blueprint",            url:"blueprintjs.com",                     cat:"react",         desc:"Palantir's React UI toolkit for data-dense desktop applications", added:"2017-01" },
  { id:82, name:"Semantic UI React",    url:"react.semantic-ui.com",              cat:"react",         desc:"Human-friendly declarative React APIs — 100+ components", added:"2016-01" },
  { id:83, name:"CoreUI React",         url:"coreui.io/react",                    cat:"react",         desc:"Bootstrap-based React library with admin dashboard templates", added:"2018-01" },
  { id:85, name:"React Bootstrap",      url:"react-bootstrap.github.io",          cat:"react",         desc:"Bootstrap rebuilt as true React components — no jQuery", added:"2019-01" },
  { id:55, name:"Gluestack",            url:"gluestack.io",                        cat:"react",         desc:"Free React + React Native component library — one codebase, two platforms", added:"2023-01" },
  { id:56, name:"React Suite",          url:"rsuitejs.com",                        cat:"react",         desc:"Comprehensive React component suite for enterprise applications", added:"2017-01" },
  { id:57, name:"Grommet",              url:"v2.grommet.io",                       cat:"react",         desc:"Accessibility-first React library backed by HPE", added:"2015-01" },
  { id:95, name:"Angular Material",     url:"material.angular.io",                 cat:"angular",       desc:"Google's official Angular UI library — Material Design components", added:"2016-01" },
  { id:96, name:"PrimeNG",              url:"primeng.org",                         cat:"angular",       desc:"The most complete Angular UI component suite — 80+ components, MIT-licensed", added:"2016-02" },
  { id:97, name:"NG-ZORRO",             url:"ng.ant.design",                       cat:"angular",       desc:"Enterprise Angular UI library based on Ant Design — 60+ components", added:"2017-01" },
  { id:58, name:"Radix UI",             url:"radix-ui.com",                        cat:"headless",      desc:"Unstyled, fully accessible React components — the foundation of shadcn/ui", added:"2021-01" },
  { id:59, name:"Headless UI",          url:"headlessui.com",                      cat:"headless",      desc:"Completely unstyled, fully accessible UI components by the Tailwind CSS team", added:"2020-01" },
  { id:60, name:"Base UI",              url:"base-ui.com",                         cat:"headless",      desc:"Unstyled React components from the MUI team — the active Radix alternative", added:"2023-01" },
  { id:61, name:"React Aria",           url:"react-spectrum.adobe.com/react-aria", cat:"headless",     desc:"Adobe's React Hooks for accessible UI primitives — rock-solid ARIA compliance", added:"2020-01" },
  { id:84, name:"Ark UI",               url:"ark-ui.com",                          cat:"headless",      desc:"45+ headless, zero-style, framework-agnostic accessible UI primitives", added:"2023-01" },
  { id:14, name:"Inspira UI",           url:"inspira-ui.com",                      cat:"multi",         desc:"Animated component library for Vue — the Vue equivalent of Magic UI", added:"2024-01" },
  { id:62, name:"shadcn-svelte",        url:"shadcn-svelte.com",                   cat:"multi",         desc:"shadcn/ui ported to Svelte — all the power, native Svelte syntax", added:"2023-01" },
  { id:63, name:"Flowbite Svelte",      url:"flowbite-svelte.com",                 cat:"multi",         desc:"Flowbite component library for Svelte with full feature parity", added:"2023-02" },
  { id:76, name:"Float UI",             url:"floatui.com",                         cat:"multi",         desc:"Free multi-framework UI components — React, Vue, Svelte, and plain HTML", added:"2023-03" },
  { id:64, name:"Vuetify",              url:"vuetifyjs.com",                       cat:"multi",         desc:"Material Design component framework for Vue — 80+ components", added:"2016-01" },
  { id:65, name:"PrimeVue",             url:"primevue.org",                        cat:"multi",         desc:"The ultimate Vue UI component library — 90+ components, 11 themes, Figma kit", added:"2019-01" },
  { id:93, name:"Nuxt UI",              url:"ui.nuxt.com",                         cat:"multi",         desc:"125+ accessible Tailwind components for Vue and Nuxt — v4 completely free", added:"2026-01" },
  { id:66, name:"Untitled UI React",    url:"untitledui.com/react",                cat:"collections",   desc:"React implementation of the Untitled UI Figma design system", added:"2026-01" },
  { id:67, name:"Tailark",              url:"tailark.com",                         cat:"collections",   desc:"Marketing-focused block library with distinctive design language", added:"2024-01" },
  { id:68, name:"React Keep Design",    url:"react.keepdesign.io",                 cat:"collections",   desc:"Design-driven React component collection with Figma workflow support", added:"2023-01" },
  { id:70, name:"Pattern Craft",        url:"patterncraft.dev",                    cat:"design-tools",  desc:"100+ CSS and Tailwind background patterns, copy-paste ready", added:"2024-01" },
  { id:71, name:"Gradienty",            url:"gradienty.codes",                     cat:"design-tools",  desc:"CSS gradient generator — browse, customize, and copy in one click", added:"2023-01" },
  { id:87, name:"Coolors",              url:"coolors.co",                          cat:"design-tools",  desc:"Fast color palette generator — create, explore, and share beautiful palettes", added:"2015-01" },
  { id:91, name:"Blobmaker",            url:"blobmaker.app",                       cat:"design-tools",  desc:"Generate unique SVG blob shapes for backgrounds and decorative elements", added:"2019-01" },
  { id:94, name:"CSS Clip-Path Maker",  url:"bennettfeely.com/clippy",             cat:"design-tools",  desc:"Visual CSS clip-path shape generator — no code needed", added:"2015-01" },
  { id:86, name:"Google Fonts",         url:"fonts.google.com",                    cat:"design-tools",  desc:"1,500+ free open-source web fonts", added:"2010-01" },
  { id:90, name:"LottieFiles",          url:"lottiefiles.com",                     cat:"design-tools",  desc:"Create, edit, preview, and share lightweight Lottie web animations", added:"2017-01" },
  { id:72, name:"Lordicon",             url:"lordicon.com",                        cat:"dev-tools",     desc:"1000+ animated Lottie icons with a free tier", added:"2020-01" },
  { id:73, name:"Lucide Icons",         url:"lucide.dev",                          cat:"dev-tools",     desc:"1000+ open-source icons — MIT-licensed, React/Vue/Svelte packages included", added:"2021-01" },
  { id:88, name:"Iconify",              url:"iconify.design",                      cat:"dev-tools",     desc:"250,000+ SVG icons from 150+ icon sets under one unified API", added:"2020-01" },
  { id:89, name:"Squoosh",              url:"squoosh.app",                         cat:"dev-tools",     desc:"Open-source browser-based image compression — no upload, fully private", added:"2018-01" },
  { id:98, name:"Pines UI",             url:"devdojo.com/pines",                   cat:"tailwind",      desc:"Copy-paste Alpine.js + Tailwind UI library — animations, sliders, modals, tooltips, accordions, zero dependencies", added:"2026-02" },
  { id:99, name:"Tamagui",              url:"tamagui.dev",                         cat:"react",         desc:"Cross-platform React + React Native style library and UI kit with an optimizing compiler", added:"2026-02" },
  { id:100,name:"NativeWind",           url:"nativewind.dev",                      cat:"multi",         desc:"Tailwind CSS as a universal style system for React Native — same utility classes on iOS, Android, and web", added:"2026-02" },
  { id:101,name:"fffuel",               url:"fffuel.co",                           cat:"design-tools",  desc:"Collection of free SVG generators for gradients, patterns, textures, blob shapes, and cool backgrounds", added:"2026-02" },
  { id:102,name:"WebGradients",         url:"webgradients.com",                    cat:"design-tools",  desc:"180 free linear gradients as CSS code, Sketch swatches, and PNG — copy-paste or download instantly", added:"2026-02" },
  { id:103,name:"CSS Gradient",         url:"cssgradient.io",                      cat:"design-tools",  desc:"Free CSS gradient generator with live preview — create linear, radial, and conic gradients visually", added:"2026-02" },
    { id:104,name:"Pinemix",              url:"pinemix.dev",                         cat:"tailwind",     desc:"Free open-source Alpine.js components styled with Tailwind CSS — accessible, interactive, copy-paste ready", added:"2026-02" },
  { id:105,name:"FrontendBaba",         url:"frontendbaba.dev",                    cat:"dev-tools",     desc:"Free browser-based frontend tools — CSS gradient, clip-path, blob, glassmorphism, shadow generators", added:"2026-02" },

  // Inspiration — curated galleries, UI references, and real-world flows
  { id:106,name:"Godly",                 url:"godly.design",                        cat:"inspiration",   desc:"Curated gallery of interesting web, app, UI, and visual design work, with sections for websites, heroes, CTAs, logos, and app screens", added:"2026-08" },
  { id:107,name:"Recent Design",         url:"recent.design",                       cat:"inspiration",   desc:"Daily curation of exceptional design, websites, interfaces, tools, typography, motion, and more", added:"2026-08" },
  { id:108,name:"Unsection",             url:"unsection.com",                       cat:"inspiration",   desc:"Curated library of 4,000+ website sections, hover effects, style filters, and a growing SVG library", added:"2026-08" },
  { id:109,name:"Detail",                url:"detail.design",                       cat:"inspiration",   desc:"Small interface details and interaction patterns covering accessibility, motion, optimization, and copywriting", added:"2026-08" },
  { id:110,name:"BentoGrids",            url:"bentogrids.com",                      cat:"inspiration",   desc:"Curated gallery of bento layouts, cards, templates, and real product examples with source links", added:"2026-08" },
  { id:111,name:"UIBits.co",             url:"uibits.co",                            cat:"inspiration",   desc:"Daily-curated UI inspiration library for discovering interface ideas and visual references", added:"2026-08" },
  { id:112,name:"Design Spells",         url:"designspells.com",                    cat:"inspiration",   desc:"Curated design details and small interactions that add polish and character to interfaces", added:"2026-08" },
  { id:113,name:"Viewport UI",            url:"viewport-ui.design",                  cat:"inspiration",   desc:"Curated UI experiences and interface references for product and web designers", added:"2026-08" },
  { id:114,name:"Lookup.design",          url:"lookup.design",                       cat:"inspiration",   desc:"Searchable collection of realistic design examples for product and interface research", added:"2026-08" },
  { id:115,name:"Design Vault",           url:"designvault.io",                      cat:"inspiration",   desc:"UI patterns and design inspiration collected from real products", added:"2026-08" },
  { id:116,name:"Interface Index",        url:"interface-index.com",                 cat:"inspiration",   desc:"Interface elements from B2B, SaaS, desktop apps, and digital services", added:"2026-08" },
  { id:117,name:"UI.live",                url:"ui.live",                              cat:"inspiration",   desc:"Community gallery for sharing and discovering notable design work", added:"2026-08" },
  { id:118,name:"Mobbin",                url:"mobbin.com",                           cat:"inspiration",   desc:"Searchable library of real mobile and web product screenshots for UI research", added:"2026-08" },
  { id:119,name:"Page Flows",            url:"pageflows.com",                       cat:"inspiration",   desc:"Real-world user-flow recordings, screens, annotations, and UX patterns from leading apps and websites", added:"2026-08" },
  { id:120,name:"SaaSFrame",             url:"saasframe.io",                        cat:"inspiration",   desc:"Large UI and UX library focused on SaaS product interfaces and website patterns", added:"2026-08" },

  // Web galleries — community showcases and award collections
  { id:121,name:"SiteInspire",           url:"siteinspire.com",                     cat:"collections",   desc:"Showcase of the web's finest design and talent, searchable by style, type, subject, and platform", added:"2026-08" },
  { id:122,name:"Httpster",              url:"httpster.net",                        cat:"collections",   desc:"Website design inspiration gallery featuring thousands of sites from designers around the world", added:"2026-08" },
  { id:123,name:"Awwwards",              url:"awwwards.com",                        cat:"collections",   desc:"Award platform and inspiration gallery for innovative websites, creative studios, and digital experiences", added:"2026-08" },
  { id:124,name:"The FWA",               url:"thefwa.com",                          cat:"collections",   desc:"Long-running awards and showcase platform for cutting-edge web design and development", added:"2026-08" },
  { id:125,name:"Hoverstates",           url:"hoverstat.es",                        cat:"collections",   desc:"Alternative design, code, and content from the wider web, curated for creative inspiration", added:"2026-08" },
  { id:126,name:"Site of Sites",         url:"siteofsites.co",                      cat:"collections",   desc:"Growing collection of go-to web design inspiration and standout website references", added:"2026-08" },
  { id:127,name:"Websitevice",           url:"websitevice.com",                     cat:"collections",   desc:"Casual website examples for practical, real-world web design inspiration", added:"2026-08" },
  { id:128,name:"Dark Mode Design",      url:"darkmodedesign.com",                  cat:"collections",   desc:"Showcase of thoughtfully designed dark-mode websites and interfaces", added:"2026-08" },
  { id:129,name:"Siiimple",              url:"siiimple.com",                        cat:"collections",   desc:"Hand-picked collection of simple, polished, and visually focused websites", added:"2026-08" },
  { id:130,name:"SiteSee",               url:"sitesee.co",                          cat:"collections",   desc:"Curated gallery of beautiful, modern websites and landing pages", added:"2026-08" },
  { id:131,name:"TOOOLS.design",          url:"toools.design",                       cat:"collections",   desc:"Curated directory of design inspiration for UI, web, mobile, SaaS, branding, illustration, motion, and more", added:"2026-08" },

  // Additional component and accessibility systems
  { id:132,name:"AlignUI",               url:"alignui.com",                         cat:"react",         desc:"React and Tailwind design system with open-source base components, Figma support, responsive layouts, and accessible patterns", added:"2026-08" },
  { id:133,name:"React Spectrum",        url:"react-spectrum.adobe.com",             cat:"react",         desc:"Adobe's React implementation and accessibility-focused design system for building robust interfaces", added:"2026-08" },
  { id:134,name:"Park UI",               url:"park-ui.com",                          cat:"react",         desc:"Beautiful components built with Ark UI and Panda CSS for React and Solid design systems", added:"2026-08" },
  { id:135,name:"Konsta UI",             url:"konstaui.com",                         cat:"multi",         desc:"MIT-licensed mobile UI components with pixel-perfect iOS and Material themes for React, Vue, and Svelte", added:"2026-08" },
  { id:136,name:"Zag.js",                url:"zagjs.com",                            cat:"headless",      desc:"Framework-agnostic state machines for accessible, interactive UI components and design systems", added:"2026-08" },

  // Trending discoveries — surfaced by Reddit and public Instagram/Reels signals
  { id:137,name:"60fps",                  url:"60fps.design",                        cat:"inspiration",   desc:"Curated library of 2,000+ UI animation and interaction details from best-in-class mobile and web apps", added:"2026-08" },
  { id:138,name:"Godly Websites",         url:"godly.website",                       cat:"inspiration",   desc:"Daily curation of exceptional design, websites, tools, typography, motion, and visual references", added:"2026-08" },
  { id:139,name:"UXArchive",              url:"uxarchive.com",                       cat:"inspiration",   desc:"Searchable archive of real mobile app flows and interaction patterns with thousands of steps to study", added:"2026-08" },
  { id:140,name:"Refero",                 url:"refero.design",                       cat:"inspiration",   desc:"Design research library of real product screens, flows, UI patterns, and searchable interface references", added:"2026-08" },
  { id:141,name:"Stark",                  url:"getstark.co",                         cat:"design-tools",  desc:"Accessibility platform for design, code, and live-product workflows with Figma, Sketch, browser, and GitHub integrations", added:"2026-08" },
  { id:142,name:"Contrast Grid",          url:"contrast-grid.eightshapes.com",       cat:"design-tools",  desc:"Fast WCAG contrast checker for testing many foreground and background color combinations at once", added:"2026-08" },
  { id:143,name:"Laws of UX",             url:"lawsofux.com",                        cat:"inspiration",   desc:"Collection of UX best practices and behavioral principles for building clearer, more usable interfaces", added:"2026-08" },
  { id:144,name:"Growth.Design",          url:"growth.design",                       cat:"inspiration",   desc:"Short, visual UX case studies and product psychology lessons delivered through interactive comics", added:"2026-08" },
  { id:145,name:"Nielsen Norman Group",   url:"nngroup.com",                          cat:"inspiration",   desc:"Research-backed UX articles, videos, courses, and usability guidance from the Nielsen Norman Group", added:"2026-08" },
  { id:146,name:"UXtweak",                url:"uxtweak.com",                         cat:"design-tools",  desc:"End-to-end UX research platform for card sorting, tree testing, prototype testing, interviews, and surveys", added:"2026-08" },
  { id:147,name:"Maze Guides",            url:"maze.co/guides",                       cat:"design-tools",  desc:"Practical guides and reports for UX research, prototype testing, interviews, and AI-moderated research", added:"2026-08" },
  { id:148,name:"Axe DevTools",           url:"deque.com/axe/devtools",               cat:"dev-tools",     desc:"Automated web and mobile accessibility testing tools for browser, IDE, CI/CD, and reporting workflows", added:"2026-08" },
  { id:149,name:"UXfolio",                url:"uxfolio.com",                          cat:"design-tools",  desc:"No-code UX portfolio builder with recruiter-friendly templates, case-study guidance, mockups, and hosting", added:"2026-08" },
  { id:150,name:"Once UI",                url:"once-ui.com",                          cat:"react",         desc:"Open-source React and Next.js design system with 100+ components, semantic layout primitives, and MIT-licensed core", added:"2026-08" },
  { id:151,name:"Naive UI",               url:"naiveui.com",                          cat:"multi",         desc:"Themeable Vue 3 component library with TypeScript support, dark mode, and a broad set of polished primitives", added:"2026-08" },
  { id:152,name:"v0",                     url:"v0.dev",                               cat:"dev-tools",     desc:"AI-powered interface builder that generates editable React and shadcn components from natural-language prompts", added:"2026-08" },
];

export const NEW_IDS       = new Set(LIBS.filter(l => l.added?.startsWith("2026")).map(l => l.id));
export const VERIFIED_DATE = "August 2026";
export const RECIPIENT = "sugumarankugan@gmail.com";
